# Generated by Django 3.2.3 on 2021-07-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('cuidad', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=200)),
                ('fecha_de_salida', models.DateTimeField(verbose_name='fecha de entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_de_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('fecha_de_salida', models.DateTimeField(verbose_name='fecha de salida')),
                ('detalle_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.detalle_inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pedido', models.DateTimeField(verbose_name='fecha de pedido')),
                ('cantidad', models.IntegerField(default=0)),
                ('codigo', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.cliente')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.orden_de_compra')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_inventario',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.inventario'),
        ),
        migrations.AddField(
            model_name='detalle_inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.producto'),
        ),
    ]
